### ISSUE TITLE
No link for where this is hosted in readme.md

### ISSUE THREAD

**Issue by lakshaysethi** [jamesctucker/teach-yourself-code#10]

**Comment by jamesctucker** [comment]
@lakshaysethi Good catch - I'll add a blurb about that!

**Comment by jamesctucker** [comment]
added in readme

**Comment by lakshaysethi** [comment]
@jamesctucker  Thanks,
 I was wondering if you have hoseted this as a demo for general public to be able to see how it looks like at the moment?
