### ISSUE TITLE
Hey James, you want to turn this into an android app?

### ISSUE THREAD

**Issue by jackson-elfers** [jamesctucker/teach-yourself-code#15]
So I found this project a while ago and have been using it to convert my web apps into android applications. It's essentially just a webview component that's pointed towards the site but it makes it really simple to put apps in the store.

If you want I'll put a repo together for you so you can check it out in android studio. Just something that could add to the project if you think it could be utilized in a mobile environment. If I find some time I'll try to help squash some other issues! -JE

[https://github.com/slymax/webview](https://github.com/slymax/webview)

**Comment by jamesctucker** [comment]
@jackson-elfers That's pretty cool! If you have time to put together a repo, I'm down!

Do you have an example Android app using Webview that I could checkout?

**Comment by jackson-elfers** [comment]
@jamesctucker Awesome! The only example that's in the store is kind of a joke I played on somebody but it's also a very simple test you could check out. Just a basic create-react-app and some api calls.
[https://play.google.com/store/apps/details?id=com.naturalinversion.morganw](https://play.google.com/store/apps/details?id=com.naturalinversion.morganw)

**Comment by jackson-elfers** [comment]
@jamesctucker So everything works, only issue being register/login, it doesn't like navigating away from the target site. I'll try to investigate a fix for that. I have it loaded on my device and it looks great!
[https://github.com/jackson-elfers/teach-yourself-code-android](https://github.com/jackson-elfers/teach-yourself-code-android)

**Comment by jackson-elfers** [comment]
A bit of a dilemma, webview doesn't play nice with oauth due to security issues. I'm going to close this for now but I might figure something out in the future. Just don't have time to mess with that atm.

**Comment by jamesctucker** [comment]
@jackson-elfers That's a bummer that oauth is causing issues. I appreciate you looking into this as an option. Maybe we'll just have to learn Flutter to create a standalone app for this ;)
