### ISSUE TITLE
Thoughts on Utility-First CSS Frameworks!

### ISSUE THREAD

**Issue by ksorv** [jamesctucker/teach-yourself-code#19]
@jamesctucker I see you've done most of the things in CSS by yourself. 
But now, I don't think we should keep on doing that.

What do you think about tailwindCSS?

Have a look [here](https://tailwindcss.com/).

**Comment by jamesctucker** [comment]
@ksorv I really like Tailwind. Currently, I'm actually using [Bulma](https://bulma.io). If you look at the some of the classes, you'll see that there are helpers in them. 

If you have time to migrate us from Bulma to Tailwind without affecting the current layout/styling, I'd be open to that.

**Comment by ksorv** [comment]
@jamesctucker 
Yeah, I did saw bulma but i didnt check its usage. I'll take a look into that. And update you with the same.

**Comment by ksorv** [comment]
I think bulma is good for out usage.
