### ISSUE TITLE
Playlists not found - graphql error??

### ISSUE THREAD

**Issue by sanvishal** [jamesctucker/teach-yourself-code#20]
I keep getting errors because playlists are not getting fetched properly. I checked the **Networks** tab in dev tools for graphql requests and `fetchPlaylists` is returning...
`message: "field "topic" not found in type: 'playlists_bool_exp'"`

Do I have to fill the database with some playlists? graphql noob here 😅

**Comment by jamesctucker** [comment]
@sanvishal Is this happening locally or online?

**Comment by sanvishal** [comment]
It's happening locally, I've fixed it by adding a row in the `playlist` table and a row in the `topics` table using the hasura console btw.

**Comment by jamesctucker** [comment]
@sanvishal glad you got it fixed. I should write some seed data so that when users populate the db with tables, there'll be initial data.
