### ISSUE TITLE
Secret not in env

### ISSUE THREAD

**Issue by maartenpeels** [jamesctucker/teach-yourself-code#22]
I guess this belongs inside the env, don't know if it's a security risk or not as I never worked with Hasura.

https://github.com/jamesctucker/teach-yourself-code/blob/ffda29b935054e0458b09f56e75832992bb89369/pages/_app.jsx#L46

**Comment by jamesctucker** [comment]
@maartenpeels Yikes, yes I need to move this to the env as well. Thanks.
