### ISSUE TITLE
Endpoint not in env

### ISSUE THREAD

**Issue by maartenpeels** [jamesctucker/teach-yourself-code#23]
I think this will not work if someone decides to deploy this project as the endpoint would change.

https://github.com/jamesctucker/teach-yourself-code/blob/ffda29b935054e0458b09f56e75832992bb89369/pages/_app.jsx#L51

**Comment by jamesctucker** [comment]
@maartenpeels Oh, good thinking! The URI should be in the env file instead. I'll update this later today.
