### ISSUE TITLE
Pausing video doesnt pause audio

### ISSUE THREAD

**Issue by jairathnem** [jamesctucker/teach-yourself-code#5]
The audio keeps playing in the background. Restarting the video causes audio overlap.

**Comment by jamesctucker** [comment]
@jairathnem Thanks for bringing this to my attention. Seems to be happening on Android only - not sure why yet. Will try to push a fix ASAP.

**Comment by jairathnem** [comment]
I had this happen on windows 10

**Comment by jamesctucker** [comment]
@jairathnem Gotcha. I just pushed a fix. I believe the issue was stemming from an autoplay hook that I was using in the video player api.

**Comment by jamesctucker** [comment]
@jairathnem Please let me know if it's resolved for you.

**Comment by jairathnem** [comment]
@jamesctucker Its resolved!
