### ISSUE TITLE
Cannot click on items in Table of contents

### ISSUE THREAD

**Issue by jairathnem** [jamesctucker/teach-yourself-code#7]
Not sure if intended functionality, but I cannot click on any content in Table of contents. 
Windows 10, Chrome Version 81.0.4044.129.

**Comment by The-Noah** [comment]
Same here. Microsoft Edge version 84.0.502.0 (Official build) canary (64-bit).

**Comment by jamesctucker** [comment]
@jairathnem this is intended. users can't access the entire playlist unless they subscribe. Thinking about changing that flow so users can watch all videos without signing in. But for now, I'll update the onboarding to explain this choice.
